server_url: http://your-host-name:8080

listen_addr: 0.0.0.0:8080

metrics_listen_addr: 0.0.0.0:9090

grpc_listen_addr: 127.0.0.1:50443

grpc_allow_insecure: false

noise:

  private_key_path: /etc/headscale/noise_private.key

prefixes:
  v4: 100.64.0.0/10
  v6: fd7a:115c:a1e0::/48

derp:
  server:

    enabled: false

    region_id: 999

    region_code: "headscale"
    region_name: "Headscale Embedded DERP"

    stun_listen_addr: "0.0.0.0:3478"

    private_key_path: /etc/headscale/derp_server_private.key


    automatically_add_embedded_derp_region: true

    ipv4: 1.2.3.4
    ipv6: 2001:db8::1

  urls:
    - https://controlplane.tailscale.com/derpmap/default

  paths: []

  auto_update_enabled: true

  update_frequency: 24h

disable_check_updates: false


ephemeral_node_inactivity_timeout: 30m

node_update_check_interval: 10s

database:
  type: sqlite

  # SQLite config
  sqlite:
    path: /etc/headscale/db.sqlite

acme_url: https://acme-v02.api.letsencrypt.org/directory

acme_email: ""

# Domain name to request a TLS certificate for:
tls_letsencrypt_hostname: ""


tls_letsencrypt_cache_dir: /etc/headscale/cache

tls_letsencrypt_challenge_type: HTTP-01

tls_letsencrypt_listen: ":http"

tls_cert_path: ""
tls_key_path: ""

log:

  format: text
  level: info

acl_policy_path: ""

dns_config:

  override_local_dns: true

  nameservers:
    - 1.1.1.1
    - 8.8.8.8

  domains: []

  magic_dns: true
  
  # `hostname.user.base_domain` (e.g., _myhost.myuser.example.com_).
  base_domain: user.headsacale.com


unix_socket: /var/run/headscale/headscale.sock
unix_socket_permission: "0770"

logtail:

  enabled: false

randomize_client_port: false